name: .NET Build Main

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
      - name: Restore Packages
        run: nuget restore OdinEye.sln
      - name: Build solution
        run: msbuild OdinEye.sln -t:rebuild -property:Configuration=Release

      - name: Run OdinEye.Client test suite
        run: .\src\OdinEye.Client.Tests\bin\Release\OdinEye.Client.Tests.exe

      - name: Run OdinEye test suite
        run: .\src\OdinEye.Tests\bin\Release\OdinEye.Tests.exe